export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';
export const GET_COUNTRIES_BY_REGION = 'Get_COUNTRIES_BY_REGION';
export const GET_COUNTRIES_BY_NAME = 'GET_COUNTRIES_BY_NAME';